import { useEffect, useRef, useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { Link, useLocation, useParams } from 'react-router-dom'

import { Button, SectionCard, SpinnerDots, textareaClass } from '../../components/ui'
import { useApiError } from '../../contexts/ApiErrorContext'
import { useToast } from '../../contexts/ToastContext'
import { EditingActions, storyApi, StorySectionBlock } from '../../features/story'
import type { SectionKey } from '../../features/story'
import { queryKeys } from '../../lib/queryKeys'
import { useQueryWithError } from '../../lib/useQueryWithError'

type StorySections = { intro: string; dev: string; climax: string; conclusion: string }

const STORY_TAB_LABELS = ['導入', '展開', 'クライマックス', '結末'] as const
const STORY_KEYS = ['intro', 'dev', 'climax', 'conclusion'] as const

function StoryEditTabs({ storyId }: { storyId: number }) {
  const { pathname } = useLocation()
  const base = `/stories/${storyId}`
  return (
    <div className="flex border-b border-[var(--border)] bg-[var(--bg)] px-5 gap-1">
      {[
        { label: 'ストーリー', path: `${base}/story` },
        { label: '相関図', path: `${base}/cast` },
      ].map((tab) => (
        <Link
          key={tab.path}
          to={tab.path}
          className={`px-4 py-2.5 text-[13px] font-medium no-underline border-b-2 transition-colors ${
            pathname === tab.path
              ? 'border-[var(--accent)] text-[var(--accent)]'
              : 'border-transparent text-[var(--text)] hover:text-[var(--text-h)]'
          }`}
        >
          {tab.label}
        </Link>
      ))}
    </div>
  )
}

export default function StoryStoryPage() {
  const { id } = useParams()
  const storyId = Number(id)
  const { showError } = useApiError()
  const { showToast } = useToast()
  const queryClient = useQueryClient()

  const [editingSection, setEditingSection] = useState<SectionKey | null>(null)
  const [submitting, setSubmitting] = useState(false)
  const [activeStoryTab, setActiveStoryTab] = useState(0)
  const [initialized, setInitialized] = useState(false)
  const [eraBg, setEraBg] = useState('')
  const [eraDraft, setEraDraft] = useState('')
  const [story, setStory] = useState<StorySections>({ intro: '', dev: '', climax: '', conclusion: '' })
  const [storyDraft, setStoryDraft] = useState<StorySections>({ intro: '', dev: '', climax: '', conclusion: '' })
  const [generating, setGenerating] = useState(false)
  const [streamText, setStreamText] = useState('')
  const streamRef = useRef<HTMLDivElement>(null)
  const { state: locationState } = useLocation()
  const autoGenerateDone = useRef(false)

  const { data, isLoading } = useQueryWithError({
    queryKey: queryKeys.story(storyId),
    queryFn: () => storyApi.getStory(storyId),
    staleTime: 0,
  })

  useEffect(() => {
    if (!data || initialized) return
    const bg = data.eraBg ?? ''
    setEraBg(bg)
    setEraDraft(bg)
    const sections = {
      intro: data.intro ?? '',
      dev: data.dev ?? '',
      climax: data.climax ?? '',
      conclusion: data.conclusion ?? '',
    }
    setStory(sections)
    setStoryDraft(sections)
    setInitialized(true)
  }, [data, initialized])

  useEffect(() => {
    if (!initialized || autoGenerateDone.current) return
    if (!(locationState as { autoGenerate?: boolean } | null)?.autoGenerate) return
    if (eraBg || story.intro || story.dev || story.climax || story.conclusion) return
    autoGenerateDone.current = true
    void handleGenerate()
  }, [initialized]) // eslint-disable-line react-hooks/exhaustive-deps

  function startEdit(section: SectionKey) {
    if (section === 'era') setEraDraft(eraBg)
    if (section === 'story') setStoryDraft(story)
    setEditingSection(section)
  }

  async function commitEdit(section: SectionKey) {
    setSubmitting(true)
    try {
      if (section === 'era') {
        setEraBg(eraDraft)
        await storyApi.updateStory(storyId, { eraBg: eraDraft })
      }
      if (section === 'story') {
        setStory(storyDraft)
        await storyApi.updateStory(storyId, storyDraft)
      }
      queryClient.invalidateQueries({ queryKey: queryKeys.story(storyId) })
      showToast('保存しました')
      setEditingSection(null)
    } catch (e) {
      showError(e)
    } finally {
      setSubmitting(false)
    }
  }

  async function handleGenerate() {
    setGenerating(true)
    setStreamText('')
    try {
      await storyApi.generateStory(storyId, (text) => {
        setStreamText((prev) => {
          const next = prev + text
          setTimeout(() => {
            if (streamRef.current) streamRef.current.scrollTop = streamRef.current.scrollHeight
          }, 0)
          return next
        })
      })
      const s = await storyApi.getStory(storyId)
      queryClient.setQueryData(queryKeys.story(storyId), s)
      const bg = s.eraBg ?? ''
      setEraBg(bg)
      setEraDraft(bg)
      const sections = {
        intro: s.intro ?? '',
        dev: s.dev ?? '',
        climax: s.climax ?? '',
        conclusion: s.conclusion ?? '',
      }
      setStory(sections)
      setStoryDraft(sections)
      showToast('ストーリーを生成しました')
    } catch (e) {
      showError(e)
    } finally {
      setGenerating(false)
    }
  }

  if (isLoading) return (
    <div className="flex flex-col flex-1 min-h-0">
      <StoryEditTabs storyId={storyId} />
      <div className="flex-1 flex justify-center pt-32">
        <SpinnerDots size="md" />
      </div>
    </div>
  )

  return (
    <div className="flex flex-col flex-1 min-h-0">
      <StoryEditTabs storyId={storyId} />
      <div className="flex flex-1 min-h-0 gap-4 p-4">

        {/* 左カラム: 時代背景 */}
        <div className="w-96 shrink-0 flex flex-col min-h-0">
          <SectionCard
            title="時代背景"
            className="flex flex-col flex-1 min-h-0"
            bodyClassName="flex-1 overflow-y-auto px-4 py-3.5"
            headerActions={
              <EditingActions
                editing={editingSection === 'era'}
                onEdit={() => startEdit('era')}
                onDone={() => commitEdit('era')}
                onCancel={() => setEditingSection(null)}
                submitting={submitting}
              />
            }
          >
            {editingSection === 'era' ? (
              <textarea
                className={`${textareaClass} min-h-[120px]`}
                value={eraDraft}
                onChange={(e) => setEraDraft(e.target.value)}
              />
            ) : (
              <p className="text-[15px] text-gray-800 leading-relaxed whitespace-pre-line">
                {eraBg || '（未設定）'}
              </p>
            )}
          </SectionCard>
        </div>

        {/* 右カラム: 歴史ストーリー */}
        <div className="flex-1 min-w-0 flex flex-col min-h-0">
          <SectionCard
            title="歴史ストーリー"
            className="flex flex-col flex-1 min-h-0"
            bodyClassName="flex flex-1 min-h-0 overflow-hidden"
            headerActions={
              <div className="flex items-center gap-2">
                <Button
                  variant="primary"
                  onClick={handleGenerate}
                  disabled={generating || editingSection !== null}
                >
                  {generating ? <SpinnerDots /> : 'AI 生成'}
                </Button>
                <EditingActions
                  editing={editingSection === 'story'}
                  onEdit={() => startEdit('story')}
                  onDone={() => commitEdit('story')}
                  onCancel={() => setEditingSection(null)}
                  submitting={submitting}
                />
              </div>
            }
          >
            {/* 縦タブ */}
            <div className="flex flex-col border-r border-[var(--border)] shrink-0 py-1">
              {STORY_TAB_LABELS.map((label, i) => (
                <button
                  key={label}
                  type="button"
                  onClick={() => setActiveStoryTab(i)}
                  className={`px-4 py-3 text-[12px] text-left border-r-2 -mr-px transition-colors whitespace-nowrap ${
                    activeStoryTab === i
                      ? 'border-[var(--accent)] text-[var(--accent)] font-semibold bg-purple-50'
                      : 'border-transparent text-[var(--text)] hover:text-[var(--text-h)] hover:bg-gray-50'
                  }`}
                >
                  {label}
                </button>
              ))}
            </div>

            {/* コンテンツ */}
            <div className="flex-1 min-w-0 overflow-y-auto px-4 py-3.5">
              {editingSection === 'story' ? (
                <textarea
                  className={`${textareaClass} min-h-[100px]`}
                  value={storyDraft[STORY_KEYS[activeStoryTab]]}
                  onChange={(e) => {
                    const key = STORY_KEYS[activeStoryTab]
                    setStoryDraft((prev) => ({ ...prev, [key]: e.target.value }))
                  }}
                />
              ) : (
                <StorySectionBlock
                  tag={STORY_TAB_LABELS[activeStoryTab]}
                  content={story[STORY_KEYS[activeStoryTab]] || '（未設定）'}
                />
              )}
            </div>
          </SectionCard>
        </div>

      </div>

      {generating && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-[var(--bg)] rounded-xl shadow-2xl w-[640px] max-h-[80vh] flex flex-col">
            <div className="flex items-center justify-between px-5 py-3 border-b border-[var(--border)]">
              <div className="flex items-center gap-2 text-[var(--text-h)] font-semibold text-[14px]">
                <SpinnerDots />
                ストーリー生成中...
              </div>
            </div>
            <div
              ref={streamRef}
              className="flex-1 overflow-y-auto p-5 text-[13px] text-[var(--text)] leading-relaxed whitespace-pre-wrap"
            >
              {streamText}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
